In [6]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
import seaborn as sns
%matplotlib inline
plt.style.use('ggplot')

In [7]:
# Creating DataFrame df from CSV StandDF
df = pd.read_csv('BinDF2', index_col=0)
df = df.drop(['C4', "C6'", "T3'", "S2'"], axis=1)

# Displaying first five results 
df.head()

C4_0  C4_1  C4_2  C4_3  C6'_0  C6'_1  T3'_0  T3'_1  T3'_2  T3'_3    ...     \
0   0.0   0.0   1.0   0.0    0.0    1.0    0.0    0.0    1.0    0.0    ...      
1   0.0   0.0   1.0   0.0    1.0    0.0    0.0    0.0    0.0    1.0    ...      
2   0.0   0.0   1.0   0.0    1.0    0.0    1.0    0.0    0.0    0.0    ...      
3   0.0   0.0   1.0   0.0    1.0    0.0    0.0    1.0    0.0    0.0    ...      
4   0.0   1.0   0.0   0.0    0.0    1.0    0.0    0.0    1.0    0.0    ...      

   Y2        C1   C2        C7  C3'       C5'       T4'       T5'       S1'  \
0   1  0.462810  1.0  0.427561  1.0  0.476417  0.534453  0.466548  0.425373   
1   0  0.589876  0.0  0.340352  0.0  0.609551  0.545989  0.850134  0.492537   
2   0  0.330579  1.0  0.223303  0.0  0.410536  0.524832  0.140946  0.417910   
3   1  0.822314  1.0  0.234437  0.0  0.401299  0.265799  0.305085  0.559701   
4   1  0.289256  1.0  0.987789  1.0  0.458048  0.393150  0.493310  0.462687   

        S3'  
0  0.457490  
1  0.854251  
2  0.137652  
3  0.340081  
4  0.570850  

[5 rows x 25 columns]

In [8]:
## Separate target variables from Data Frame 
## Using .ravel() to create a contiguous flattened array to change the shape of (n_samples)

####ERROR for.len()---vector y was passed when a 1d array was expected. 
####Please change the shape of y to (n_samples, ), for example using ravel().
  ##y = column_or_1d(y, warn=True)
    
y1 =df.loc[:, ['Y1']].values.ravel()
y2 =df.loc[:, ['Y2']].values.ravel()

## Drop target variables from Data Frame 
df = df.drop(['Y1','Y2'], axis=1)

## Drop C6' from DF1 
df1 = df.drop(["C6'_0", "C6'_1"], axis=1)

In [9]:
# Recursive Feature Elimination for Y1 target 
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# create a base classifier used to evaluate a subset of attributes
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(df1, y1)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[False False False False False False False False False False False False
 False False  True False  True False False  True False]
[ 9  8 18 17  4 16  7 10 14 15  3  2  5 12  1 13  1  6 11  1 19]


/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: 

In [10]:
# Recursive Feature Elimination for Y2 target 
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# create a base classifier used to evaluate a subset of attributes
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(df, y2)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[False False False False False  True False False False False False False
 False  True False False False False  True False False False False]
[ 8 10 20 16  4  1 21 15 17  7  2 13 18  1 14  5  6 19  1  3  9 11 12]


/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: 

In [27]:

# Checking how many features this dataset have

print(df.shape[1])

13


In [29]:
for i in range(1, df.shape[1]+1):
    print(i)
    # create a base classifier used to evaluate a subset of attributes
    model = LogisticRegression()
    # create the RFE model and select 3 attributes; Target Variable Y1
    rfe = RFE(model, i)
    rfe = rfe.fit(df1, y1)
    # summarize the selection of the attributes
    print('Model with the best', i, 'features')
    print(rfe.support_)
    print(rfe.ranking_)

1
Model with the best 1 features
[False False False False False False False False False False  True False]
[ 7  9  2  5 10  6  8  3 11  4  1 12]
2
Model with the best 2 features
[False False  True False False False False False False False  True False]
[ 6  8  1  4  9  5  7  2 10  3  1 11]
3
Model with the best 3 features
[False False  True False False False False  True False False  True False]
[ 5  7  1  3  8  4  6  1  9  2  1 10]
4
Model with the best 4 features
[False False  True False False False False  True False  True  True False]
[4 6 1 2 7 3 5 1 8 1 1 9]
5
Model with the best 5 features
[False False  True  True False False False  True False  True  True False]
[3 5 1 1 6 2 4 1 7 1 1 8]
6
Model with the best 6 features
[False False  True  True False  True False  True False  True  True False]
[2 4 1 1 5 1 3 1 6 1 1 7]
7
Model with the best 7 features
[ True False  True  True False  True False  True False  True  True False]
[1 3 1 1 4 1 2 1 5 1 1 6]
8
Model with the best 8 features


In [30]:
for i in range(1, df.shape[1]+1):
    print(i)
    # create a base classifier used to evaluate a subset of attributes
    model = LogisticRegression()
    # create the RFE model and select 3 attributes; Target Variable Y2
    rfe = RFE(model, i)
    rfe = rfe.fit(df, y2)
    # summarize the selection of the attributes
    print('Model with the best', i, 'features')
    print(rfe.support_)
    print(rfe.ranking_)

1
Model with the best 1 features
[False False False False False False  True False False False False False
 False]
[12  5  3  6 13  4  1  7  8  9 10  2 11]
2
Model with the best 2 features
[False False False False False False  True False False False False  True
 False]
[11  4  2  5 12  3  1  6  7  8  9  1 10]
3
Model with the best 3 features
[False False  True False False False  True False False False False  True
 False]
[10  3  1  4 11  2  1  5  6  7  8  1  9]
4
Model with the best 4 features
[False False  True False False  True  True False False False False  True
 False]
[ 9  2  1  3 10  1  1  4  5  6  7  1  8]
5
Model with the best 5 features
[False  True  True False False  True  True False False False False  True
 False]
[8 1 1 2 9 1 1 3 4 5 6 1 7]
6
Model with the best 6 features
[False  True  True  True False  True  True False False False False  True
 False]
[7 1 1 1 8 1 1 2 3 4 5 1 6]
7
Model with the best 7 features
[False  True  True  True False  True  True  True False False Fa

In [31]:
###extra trees classifier to report feature importance, 
###and use an abitrary 0.4 value to filter the features
#The idea is whatever features passing the threshold would be selected

# Feature Importance
from sklearn import datasets
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier

# fit an Extra Trees model to the data; Target Variable Y1

model = ExtraTreesClassifier()
model.fit(df1, y1)
# display the relative importance of each attribute
print(model.feature_importances_ > .5)


[False False False False False False False False False False False False]


In [32]:
###extra trees classifier to report feature importance, 
###and use an abitrary 0.4 value to filter the features
#The idea is whatever features passing the threshold would be selected

# Feature Importance
from sklearn import datasets
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier

# fit an Extra Trees model to the data; Target Variable 

model = ExtraTreesClassifier()
model.fit(df, y2)
# display the relative importance of each attribute
print(model.feature_importances_ > .5)

[False False False False False False False False False False False False
 False]
