In [1]:

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
import seaborn as sns


In [9]:
# Creating DataFrame df from CSV StandDF
df = pd.read_csv('ReadyDF1', index_col=0)

# Displaying first five results 
df.head()

Y1  Y2        C1   C2        C4        C7  C3'       C5'       C6'  \
0   0   1  2.086360  1.0  0.029074  1.710498    1  1.351792  1.306758   
1   1   0  2.413300  0.0 -0.013352  1.413903    0  2.487306  0.000000   
2   1   0  1.954243  1.0  0.020715  0.867939    0  1.214656  0.000000   
3   1   1  2.320146  1.0  0.020023  0.930745    0  1.193831  0.000000   
4   0   1  1.903090  1.0 -0.034895  2.800922    1  1.315407  1.195813   

        T4'       T3'       T5'       S1'       S2'       S3'  
0  0.640426  0.979660 -1.241958  0.172661 -2.012621 -1.937792  
1  0.644753  1.275142 -1.031589  0.180641 -1.696991 -1.706058  
2  0.636816  0.630286 -1.568923  0.171728 -2.562293 -2.302656  
3  0.539634  0.792975 -1.374089  0.187973 -2.309955 -2.039414  
4  0.587413  1.045896 -1.223474  0.177183 -1.907621 -1.858090

In [10]:
## Separate target variables from Data Frame 
## Using .ravel() to create a contiguous flattened array to change the shape 

    
y1 =df.loc[:, ['Y1']].values.ravel()
y2 =df.loc[:, ['Y2']].values.ravel()

## Drop target variables from Data Frame 
df = df.drop(['Y1','Y2'], axis=1)

## Drop C6' from DF1 
df1 = df.drop(["C6'"], axis=1)

In [11]:
# Recursive Feature Elimination for Y1 target 
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# create a base classifier used to evaluate a subset of attributes
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(df1, y1)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[False False  True False False False  True False False False  True False]
[ 6  4  1  9  5  7  1  8  2  3  1 10]


In [12]:
# Recursive Feature Elimination for Y2 target 
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# create a base classifier used to evaluate a subset of attributes
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(df, y2)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[False False  True False False False  True False False False False  True
 False]
[ 9  4  1  8 11  6  1  5  3  7 10  1  2]


In [13]:

# Checking how many features this dataset have

print(df.shape[1])

13


In [14]:
for i in range(1, df.shape[1]+1):
    print(i)
    # create a base classifier used to evaluate a subset of attributes
    model = LogisticRegression()
    # create the RFE model and select 3 attributes; Target Variable Y1
    rfe = RFE(model, i)
    rfe = rfe.fit(df1, y1)
    # summarize the selection of the attributes
    print('Model with the best', i, 'features')
    print(rfe.support_)
    print(rfe.ranking_)

1
Model with the best 1 features
[False False False False False False  True False False False False False]
[ 8  6  2 11  7  9  1 10  4  5  3 12]
2
Model with the best 2 features
[False False  True False False False  True False False False False False]
[ 7  5  1 10  6  8  1  9  3  4  2 11]
3
Model with the best 3 features
[False False  True False False False  True False False False  True False]
[ 6  4  1  9  5  7  1  8  2  3  1 10]
4
Model with the best 4 features
[False False  True False False False  True False  True False  True False]
[5 3 1 8 4 6 1 7 1 2 1 9]
5
Model with the best 5 features
[False False  True False False False  True False  True  True  True False]
[4 2 1 7 3 5 1 6 1 1 1 8]
6
Model with the best 6 features
[False  True  True False False False  True False  True  True  True False]
[3 1 1 6 2 4 1 5 1 1 1 7]
7
Model with the best 7 features
[False  True  True False  True False  True False  True  True  True False]
[2 1 1 5 1 3 1 4 1 1 1 6]
8
Model with the best 8 features


In [15]:
for i in range(1, df.shape[1]+1):
    print(i)
    # create a base classifier used to evaluate a subset of attributes
    model = LogisticRegression()
    # create the RFE model and select 3 attributes; Target Variable Y2
    rfe = RFE(model, i)
    rfe = rfe.fit(df, y2)
    # summarize the selection of the attributes
    print('Model with the best', i, 'features')
    print(rfe.support_)
    print(rfe.ranking_)

1
Model with the best 1 features
[False False False False False False  True False False False False False
 False]
[11  6  2 10 13  8  1  7  5  9 12  3  4]
2
Model with the best 2 features
[False False  True False False False  True False False False False False
 False]
[10  5  1  9 12  7  1  6  4  8 11  2  3]
3
Model with the best 3 features
[False False  True False False False  True False False False False  True
 False]
[ 9  4  1  8 11  6  1  5  3  7 10  1  2]
4
Model with the best 4 features
[False False  True False False False  True False False False False  True
  True]
[ 8  3  1  7 10  5  1  4  2  6  9  1  1]
5
Model with the best 5 features
[False False  True False False False  True False  True False False  True
  True]
[7 2 1 6 9 4 1 3 1 5 8 1 1]
6
Model with the best 6 features
[False  True  True False False False  True False  True False False  True
  True]
[6 1 1 5 8 3 1 2 1 4 7 1 1]
7
Model with the best 7 features
[False  True  True False False False  True  True  True False Fa