In [14]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
import seaborn as sns
%matplotlib inline
plt.style.use('ggplot')

In [15]:
# Creating DataFrame df from CSV StandDF
df = pd.read_csv('BinDF1', index_col=0)
# Displaying first five results 
df.head()

C4_0  C4_1  C4_2  C4_3  C6'_0  C6'_1  C6'_2  T4'_0  T4'_1  T4'_2    ...     \
0   0.0   0.0   1.0   0.0    0.0    0.0    1.0    0.0    0.0    1.0    ...      
1   0.0   1.0   0.0   0.0    1.0    0.0    0.0    0.0    0.0    1.0    ...      
2   0.0   0.0   1.0   0.0    1.0    0.0    0.0    0.0    0.0    1.0    ...      
3   0.0   0.0   1.0   0.0    1.0    0.0    0.0    0.0    1.0    0.0    ...      
4   0.0   1.0   0.0   0.0    0.0    1.0    0.0    0.0    1.0    0.0    ...      

         C7  C3'       C5'       C6'       T4'       T3'       T5'       S1'  \
0  1.710498    1  1.351792  1.306758  0.640426  0.979660 -1.241958  0.172661   
1  1.413903    0  2.487306  0.000000  0.644753  1.275142 -1.031589  0.180641   
2  0.867939    0  1.214656  0.000000  0.636816  0.630286 -1.568923  0.171728   
3  0.930745    0  1.193831  0.000000  0.539634  0.792975 -1.374089  0.187973   
4  2.800922    1  1.315407  1.195813  0.587413  1.045896 -1.223474  0.177183   

        S2'       S3'  
0 -2.012621 -1.937792  
1 -1.696991 -1.706058  
2 -2.562293 -2.302656  
3 -2.309955 -2.039414  
4 -1.907621 -1.858090  

[5 rows x 30 columns]

In [16]:
df = df.drop(['C4', "C6'", "T4'", "S2'"], axis=1)
df.head()

C4_0  C4_1  C4_2  C4_3  C6'_0  C6'_1  C6'_2  T4'_0  T4'_1  T4'_2    ...     \
0   0.0   0.0   1.0   0.0    0.0    0.0    1.0    0.0    0.0    1.0    ...      
1   0.0   1.0   0.0   0.0    1.0    0.0    0.0    0.0    0.0    1.0    ...      
2   0.0   0.0   1.0   0.0    1.0    0.0    0.0    0.0    0.0    1.0    ...      
3   0.0   0.0   1.0   0.0    1.0    0.0    0.0    0.0    1.0    0.0    ...      
4   0.0   1.0   0.0   0.0    0.0    1.0    0.0    0.0    1.0    0.0    ...      

   Y2        C1   C2        C7  C3'       C5'       T3'       T5'       S1'  \
0   1  2.086360  1.0  1.710498    1  1.351792  0.979660 -1.241958  0.172661   
1   0  2.413300  0.0  1.413903    0  2.487306  1.275142 -1.031589  0.180641   
2   0  1.954243  1.0  0.867939    0  1.214656  0.630286 -1.568923  0.171728   
3   1  2.320146  1.0  0.930745    0  1.193831  0.792975 -1.374089  0.187973   
4   1  1.903090  1.0  2.800922    1  1.315407  1.045896 -1.223474  0.177183   

        S3'  
0 -1.937792  
1 -1.706058  
2 -2.302656  
3 -2.039414  
4 -1.858090  

[5 rows x 26 columns]

In [17]:
## Separate target variables from Data Frame 
## Using .ravel() to create a contiguous flattened array to change the shape of (n_samples)

####ERROR for.len()---vector y was passed when a 1d array was expected. 
####Please change the shape of y to (n_samples, ), for example using ravel().
  ##y = column_or_1d(y, warn=True)
    
y1 =df.loc[:, ['Y1']].values.ravel()
y2 =df.loc[:, ['Y2']].values.ravel()

## Drop target variables from Data Frame 
df = df.drop(['Y1','Y2'], axis=1)

## Drop C6' from DF1 
df1 = df.drop(["C6'_0", "C6'_1", "C6'_2"], axis=1)

In [18]:
# Recursive Feature Elimination for Y1 target 
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# create a base classifier used to evaluate a subset of attributes
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(df1, y1)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[False False False False False False False False False  True False  True
 False  True False False False False False False False]
[ 4 11 18 19  2 17 16 10  6  1 14  1  8  1  7 12  9 15  5  3 13]


/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: 

In [19]:
# Recursive Feature Elimination for Y2 target 
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# create a base classifier used to evaluate a subset of attributes
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(df, y2)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[False False False False False  True  True False False False False False
  True False False False False False False False False False False False]
[19  2 12  7  4  1  1 11 16 17  5 18  1 14  3 15  6 20 22 10 13  8 21  9]


/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: 

In [20]:

# Checking how many features this dataset have

print(df.shape[1])

24


In [21]:
for i in range(1, df.shape[1]+1):
    print(i)
    # create a base classifier used to evaluate a subset of attributes
    model = LogisticRegression()
    # create the RFE model and select 3 attributes; Target Variable Y1
    rfe = RFE(model, i)
    rfe = rfe.fit(df1, y1)
    # summarize the selection of the attributes
    print('Model with the best', i, 'features')
    print(rfe.support_)
    print(rfe.ranking_)

1
Model with the best 1 features
[False False False False False False False False False False False  True
 False False False False False False False False False]
[ 6 13 20 21  4 19 18 12  8  2 16  1 10  3  9 14 11 17  7  5 15]
2
Model with the best 2 features
[False False False False False False False False False  True False  True
 False False False False False False False False False]
[ 5 12 19 20  3 18 17 11  7  1 15  1  9  2  8 13 10 16  6  4 14]
3
Model with the best 3 features
[False False False False False False False False False  True False  True
 False  True False False False False False False False]
[ 4 11 18 19  2 17 16 10  6  1 14  1  8  1  7 12  9 15  5  3 13]
4
Model with the best 4 features
[False False False False  True False False False False  True False  True
 False  True False False False False False False False]
[ 3 10 17 18  1 16 15  9  5  1 13  1  7  1  6 11  8 14  4  2 12]
5


/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: 

Model with the best 5 features
[False False False False  True False False False False  True False  True
 False  True False False False False False  True False]
[ 2  9 16 17  1 15 14  8  4  1 12  1  6  1  5 10  7 13  3  1 11]
6
Model with the best 6 features
[ True False False False  True False False False False  True False  True
 False  True False False False False False  True False]
[ 1  8 15 16  1 14 13  7  3  1 11  1  5  1  4  9  6 12  2  1 10]
7
Model with the best 7 features
[ True False False False  True False False False False  True False  True
 False  True False False False False  True  True False]
[ 1  7 14 15  1 13 12  6  2  1 10  1  4  1  3  8  5 11  1  1  9]
8
Model with the best 8 features
[ True False False False  True False False False  True  True False  True
 False  True False False False False  True  True False]
[ 1  6 13 14  1 12 11  5  1  1  9  1  3  1  2  7  4 10  1  1  8]
9
Model with the best 9 features
[ True False False False  True False False False  True  True 

/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: 

Model with the best 10 features
[ True False False False  True False False False  True  True False  True
  True  True  True False False False  True  True False]
[ 1  4 11 12  1 10  9  3  1  1  7  1  1  1  1  5  2  8  1  1  6]
11
Model with the best 11 features
[ True False False False  True False False False  True  True False  True
  True  True  True False  True False  True  True False]
[ 1  3 10 11  1  9  8  2  1  1  6  1  1  1  1  4  1  7  1  1  5]
12
Model with the best 12 features
[ True False False False  True False False  True  True  True False  True
  True  True  True False  True False  True  True False]
[ 1  2  9 10  1  8  7  1  1  1  5  1  1  1  1  3  1  6  1  1  4]
13
Model with the best 13 features
[ True  True False False  True False False  True  True  True False  True
  True  True  True False  True False  True  True False]
[1 1 8 9 1 7 6 1 1 1 4 1 1 1 1 2 1 5 1 1 3]
14
Model with the best 14 features
[ True  True False False  True False False  True  True  True False  True


/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: 

In [22]:
for i in range(1, df.shape[1]+1):
    print(i)
    # create a base classifier used to evaluate a subset of attributes
    model = LogisticRegression()
    # create the RFE model and select 3 attributes; Target Variable Y2
    rfe = RFE(model, i)
    rfe = rfe.fit(df, y2)
    # summarize the selection of the attributes
    print('Model with the best', i, 'features')
    print(rfe.support_)
    print(rfe.ranking_)

1
Model with the best 1 features
[False False False False False False  True False False False False False
 False False False False False False False False False False False False]
[21  4 14  9  6  2  1 13 18 19  7 20  3 16  5 17  8 22 24 12 15 10 23 11]
2
Model with the best 2 features
[False False False False False  True  True False False False False False
 False False False False False False False False False False False False]
[20  3 13  8  5  1  1 12 17 18  6 19  2 15  4 16  7 21 23 11 14  9 22 10]
3
Model with the best 3 features
[False False False False False  True  True False False False False False
  True False False False False False False False False False False False]
[19  2 12  7  4  1  1 11 16 17  5 18  1 14  3 15  6 20 22 10 13  8 21  9]
4


/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: 

Model with the best 4 features
[False  True False False False  True  True False False False False False
  True False False False False False False False False False False False]
[18  1 11  6  3  1  1 10 15 16  4 17  1 13  2 14  5 19 21  9 12  7 20  8]
5
Model with the best 5 features
[False  True False False False  True  True False False False False False
  True False  True False False False False False False False False False]
[17  1 10  5  2  1  1  9 14 15  3 16  1 12  1 13  4 18 20  8 11  6 19  7]
6
Model with the best 6 features
[False  True False False  True  True  True False False False False False
  True False  True False False False False False False False False False]
[16  1  9  4  1  1  1  8 13 14  2 15  1 11  1 12  3 17 19  7 10  5 18  6]
7
Model with the best 7 features
[False  True False False  True  True  True False False False  True False
  True False  True False False False False False False False False False]
[15  1  8  3  1  1  1  7 12 13  1 14  1 10  1 11  2 16 18  6

/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: 

Model with the best 8 features
[False  True False False  True  True  True False False False  True False
  True False  True False  True False False False False False False False]
[14  1  7  2  1  1  1  6 11 12  1 13  1  9  1 10  1 15 17  5  8  3 16  4]
9
Model with the best 9 features
[False  True False  True  True  True  True False False False  True False
  True False  True False  True False False False False False False False]
[13  1  6  1  1  1  1  5 10 11  1 12  1  8  1  9  1 14 16  4  7  2 15  3]
10
Model with the best 10 features
[False  True False  True  True  True  True False False False  True False
  True False  True False  True False False False False  True False False]
[12  1  5  1  1  1  1  4  9 10  1 11  1  7  1  8  1 13 15  3  6  1 14  2]
11
Model with the best 11 features
[False  True False  True  True  True  True False False False  True False
  True False  True False  True False False False False  True False  True]
[11  1  4  1  1  1  1  3  8  9  1 10  1  6  1  7  1 12 1

/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: 

Model with the best 13 features
[False  True False  True  True  True  True  True False False  True False
  True False  True False  True False False  True False  True False  True]
[ 9  1  2  1  1  1  1  1  6  7  1  8  1  4  1  5  1 10 12  1  3  1 11  1]
14
Model with the best 14 features
[False  True  True  True  True  True  True  True False False  True False
  True False  True False  True False False  True False  True False  True]
[ 8  1  1  1  1  1  1  1  5  6  1  7  1  3  1  4  1  9 11  1  2  1 10  1]
15
Model with the best 15 features
[False  True  True  True  True  True  True  True False False  True False
  True False  True False  True False False  True  True  True False  True]
[ 7  1  1  1  1  1  1  1  4  5  1  6  1  2  1  3  1  8 10  1  1  1  9  1]
16
Model with the best 16 features
[False  True  True  True  True  True  True  True False False  True False
  True  True  True False  True False False  True  True  True False  True]
[6 1 1 1 1 1 1 1 3 4 1 5 1 1 1 2 1 7 9 1 1 1 8 1]
17


/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: 

In [23]:
###extra trees classifier to report feature importance, 
###and use an abitrary 0.4 value to filter the features
#The idea is whatever features passing the threshold would be selected

# Feature Importance
from sklearn import datasets
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier

# fit an Extra Trees model to the data; Target Variable Y1

model = ExtraTreesClassifier()
model.fit(df1, y1)
# display the relative importance of each attribute
print(model.feature_importances_ > .5)


[False False False False False False False False False False False False
 False False False False False False False False False]


/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [24]:
###extra trees classifier to report feature importance, 
###and use an abitrary 0.4 value to filter the features
#The idea is whatever features passing the threshold would be selected

# Feature Importance
from sklearn import datasets
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier

# fit an Extra Trees model to the data; Target Variable 

model = ExtraTreesClassifier()
model.fit(df, y2)
# display the relative importance of each attribute
print(model.feature_importances_ > .5)

[False False False False False False False False False False False False
 False False False False False False False False False False False False]


/home/jupyter-jhoffmann/.local/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
